services:
  - type: web
    name: naijahandy-api
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run db:deploy && npm run db:fix && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
