import type { Artisan, Category, Booking } from '@/types'

export const DEFAULT_AVATAR = '/avatars/default.svg'

// ─── MOCK DATA ────────────────────────────────────────────────────────────────
// Replace all exports here with real API calls once the backend is live.
// Example: export const fetchArtisans = () => axios.get('/api/artisans')

export const ARTISANS: Artisan[] = [
  {
    id: 'mock-1',
    name: 'Emeka Okafor',
    profession: 'Master Plumber',
    city: 'Lagos, VI',
    rating: 4.9,
    reviews: 134,
    hourlyRate: 8500,
    verified: true,
    verificationStatus: 'UNVERIFIED',
    verificationDocUrl: null,
    bio: 'Over 12 years of experience fixing residential and commercial plumbing across Lagos. Specialise in pipe installations and emergency repairs.',
    avatar: 'https://images.unsplash.com/photo-1618077360395-f3068be8e001?w=120&h=120&fit=crop&auto=format',
    cover: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=900&h=300&fit=crop&auto=format',
    category: 'Plumbing',
    available: true,
    isDemo: false,
    portfolio: [
      { id: 'mock-p1', imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop&auto=format' },
      { id: 'mock-p2', imageUrl: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=400&h=300&fit=crop&auto=format' },
      { id: 'mock-p3', imageUrl: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&h=300&fit=crop&auto=format' },
    ],
    services: [
      { name: 'Pipe Installation', rate: 8500 },
      { name: 'Emergency Leak Repair', rate: 12000 },
      { name: 'Bathroom Fitting', rate: 45000 },
      { name: 'Drain Cleaning', rate: 6000 },
    ],
    completedJobsCount: 0,
    recentCompletedJobs: [],
    reviews_list: [
      { name: 'Chisom Eze', rating: 5, comment: 'Fixed our burst pipe in under an hour. Absolutely professional!', date: '2 weeks ago', avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=40&h=40&fit=crop&auto=format' },
      { name: 'Bayo Adeleke', rating: 5, comment: 'Emeka is incredibly skilled and punctual. Highly recommended.', date: '1 month ago', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=40&h=40&fit=crop&auto=format' },
      { name: 'Nneka Obi', rating: 4, comment: 'Good work overall, though a bit pricey for the job.', date: '2 months ago', avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=40&h=40&fit=crop&auto=format' },
    ],
  },
  {
    id: 'mock-2',
    name: 'Fatima Aliyu',
    profession: 'Electrician',
    city: 'Abuja, Wuse',
    rating: 4.8,
    reviews: 89,
    hourlyRate: 7500,
    verified: true,
    verificationStatus: 'UNVERIFIED',
    verificationDocUrl: null,
    bio: 'Certified electrical engineer with COREN accreditation. Residential wiring, industrial installations, and solar panel setups.',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&h=120&fit=crop&auto=format',
    cover: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=900&h=300&fit=crop&auto=format',
    category: 'Electrical',
    available: true,
    isDemo: false,
    portfolio: [],
    services: [],
    completedJobsCount: 0,
    recentCompletedJobs: [],
    reviews_list: [],
  },
  {
    id: 'mock-3',
    name: 'Chidi Nwosu',
    profession: 'Carpenter & Joiner',
    city: 'Port Harcourt',
    rating: 4.7,
    reviews: 62,
    hourlyRate: 6500,
    verified: true,
    verificationStatus: 'UNVERIFIED',
    verificationDocUrl: null,
    bio: 'Custom furniture design and woodworking for homes and offices. 9 years building bespoke pieces across the South-South.',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&h=120&fit=crop&auto=format',
    cover: '',
    category: 'Carpentry',
    available: false,
    isDemo: false,
    portfolio: [],
    services: [],
    completedJobsCount: 0,
    recentCompletedJobs: [],
    reviews_list: [],
  },
  {
    id: 'mock-4',
    name: 'Amaka Okonkwo',
    profession: 'Painter & Decorator',
    city: 'Lagos, Yaba',
    rating: 4.9,
    reviews: 201,
    hourlyRate: 5000,
    verified: true,
    verificationStatus: 'UNVERIFIED',
    verificationDocUrl: null,
    bio: 'Interior and exterior painting specialist. Colour consultation, textured finishes, and Venetian plaster applications.',
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=120&h=120&fit=crop&auto=format',
    cover: '',
    category: 'Painting',
    available: true,
    isDemo: false,
    portfolio: [],
    services: [],
    completedJobsCount: 0,
    recentCompletedJobs: [],
    reviews_list: [],
  },
  {
    id: 'mock-5',
    name: 'Yusuf Garba',
    profession: 'Auto Mechanic',
    city: 'Kano, Sabon Gari',
    rating: 4.6,
    reviews: 47,
    hourlyRate: 5500,
    verified: false,
    verificationStatus: 'UNVERIFIED',
    verificationDocUrl: null,
    bio: 'Toyota & Nissan certified mechanic. Engine diagnostics, gearbox overhaul, AC servicing, and tyre replacements.',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&h=120&fit=crop&auto=format',
    cover: '',
    category: 'Auto Repair',
    available: true,
    isDemo: false,
    portfolio: [],
    services: [],
    completedJobsCount: 0,
    recentCompletedJobs: [],
    reviews_list: [],
  },
  {
    id: 'mock-6',
    name: 'Ngozi Adeyemi',
    profession: 'Interior Designer',
    city: 'Lagos, Lekki',
    rating: 5.0,
    reviews: 58,
    hourlyRate: 15000,
    verified: true,
    verificationStatus: 'UNVERIFIED',
    verificationDocUrl: null,
    bio: 'Award-winning interior designer with projects across West Africa. Space planning, furniture sourcing, and full project management.',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&h=120&fit=crop&auto=format',
    cover: '',
    category: 'Carpentry',
    available: true,
    isDemo: false,
    portfolio: [],
    services: [],
    completedJobsCount: 0,
    recentCompletedJobs: [],
    reviews_list: [],
  },
]

export const CATEGORIES: Category[] = [
  { name: 'Plumbing', count: 0 },
  { name: 'Electrical', count: 0 },
  { name: 'Carpentry', count: 0 },
  { name: 'Painting', count: 0 },
  { name: 'Auto Repair', count: 0 },
  { name: 'Home Cleaning', count: 0 },
  { name: 'Tailoring', count: 0 },
  { name: 'Tiling & Flooring', count: 0 },
  { name: 'Air Conditioning', count: 0 },
  { name: 'Welding & Metalwork', count: 0 },
  { name: 'Electronics Repair', count: 0 },
]

export const BOOKINGS: Booking[] = [
  { id: 'BK-001', artisanId: 'a1', artisan: 'Emeka Okafor', profession: 'Plumber', date: 'Tue, 30 Jul 2026', dateISO: '2026-07-30T09:00:00.000Z', time: '9:00 AM', description: 'Kitchen faucet replacement', amount: 17000, status: 'Confirmed', avatar: 'https://images.unsplash.com/photo-1618077360395-f3068be8e001?w=48&h=48&fit=crop&auto=format', paymentStatus: 'PAID', isUrgent: false },
  { id: 'BK-002', artisanId: 'a2', artisan: 'Fatima Aliyu', profession: 'Electrician', date: 'Fri, 2 Aug 2026', dateISO: '2026-08-02T14:00:00.000Z', time: '2:00 PM', description: 'Rewire living room sockets', amount: 15000, status: 'Pending', avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=48&h=48&fit=crop&auto=format', paymentStatus: 'UNPAID', isUrgent: false },
  { id: 'BK-003', artisanId: 'a3', artisan: 'Amaka Okonkwo', profession: 'Painter', date: 'Mon, 12 Aug 2026', dateISO: '2026-08-12T08:00:00.000Z', time: '8:00 AM', description: 'Paint 3-bedroom apartment interior', amount: 30000, status: 'Pending', avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=48&h=48&fit=crop&auto=format', paymentStatus: 'UNPAID', isUrgent: false },
  { id: 'BK-004', artisanId: 'a4', artisan: 'Chidi Nwosu', profession: 'Carpenter', date: 'Sat, 19 Jul 2026', dateISO: '2026-07-19T10:00:00.000Z', time: '10:00 AM', description: 'Custom bookshelf build', amount: 26000, status: 'Completed', avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=48&h=48&fit=crop&auto=format', paymentStatus: 'PAID', isUrgent: false },
  { id: 'BK-005', artisanId: 'a5', artisan: 'Yusuf Garba', profession: 'Auto Mechanic', date: 'Wed, 9 Jul 2026', dateISO: '2026-07-09T11:00:00.000Z', time: '11:00 AM', description: 'Brake pad replacement', amount: 11000, status: 'Cancelled', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=48&h=48&fit=crop&auto=format', paymentStatus: 'REFUNDED', isUrgent: false },
]

export const NIGERIAN_CITIES = [
  'Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa', 'Benue',
  'Borno', 'Cross River', 'Delta', 'Ebonyi', 'Edo', 'Ekiti', 'Enugu',
  'Gombe', 'Imo', 'Jigawa', 'Kaduna', 'Kano', 'Katsina', 'Kebbi', 'Kogi',
  'Kwara', 'Lagos', 'Nasarawa', 'Niger', 'Ogun', 'Ondo', 'Osun', 'Oyo',
  'Plateau', 'Rivers', 'Sokoto', 'Taraba', 'Yobe', 'Zamfara', 'Abuja (FCT)',
]
