import type { Artisan, Category } from '@/types'

// ─── MOCK DATA ────────────────────────────────────────────────────────────────
// Replace all exports here with real API calls once the backend is live.
// Example: export const fetchArtisans = () => axios.get('/api/artisans')

export const ARTISANS: Artisan[] = [
  {
    id: 'mock-1',
    name: 'Emeka Okafor',
    profession: 'Master Plumber',
    city: 'Lagos, VI',
    rating: 4.9,
    reviews: 134,
    hourlyRate: 8500,
    verified: true,
    bio: 'Over 12 years of experience fixing residential and commercial plumbing across Lagos. Specialise in pipe installations and emergency repairs.',
    avatar: 'https://images.unsplash.com/photo-1618077360395-f3068be8e001?w=120&h=120&fit=crop&auto=format',
    cover: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=900&h=300&fit=crop&auto=format',
    category: 'Plumbing',
    available: true,
    portfolio: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=400&h=300&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&h=300&fit=crop&auto=format',
    ],
    services: [
      { name: 'Pipe Installation', rate: 8500 },
      { name: 'Emergency Leak Repair', rate: 12000 },
      { name: 'Bathroom Fitting', rate: 45000 },
      { name: 'Drain Cleaning', rate: 6000 },
    ],
    reviews_list: [
      { name: 'Chisom Eze', rating: 5, comment: 'Fixed our burst pipe in under an hour. Absolutely professional!', date: '2 weeks ago', avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=40&h=40&fit=crop&auto=format' },
      { name: 'Bayo Adeleke', rating: 5, comment: 'Emeka is incredibly skilled and punctual. Highly recommended.', date: '1 month ago', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=40&h=40&fit=crop&auto=format' },
      { name: 'Nneka Obi', rating: 4, comment: 'Good work overall, though a bit pricey for the job.', date: '2 months ago', avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=40&h=40&fit=crop&auto=format' },
    ],
  },
  {
    id: 'mock-2',
    name: 'Fatima Aliyu',
    profession: 'Electrician',
    city: 'Abuja, Wuse',
    rating: 4.8,
    reviews: 89,
    hourlyRate: 7500,
    verified: true,
    bio: 'Certified electrical engineer with COREN accreditation. Residential wiring, industrial installations, and solar panel setups.',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&h=120&fit=crop&auto=format',
    cover: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=900&h=300&fit=crop&auto=format',
    category: 'Electrical',
    available: true,
    portfolio: [],
    services: [],
    reviews_list: [],
  },
  {
    id: 'mock-3',
    name: 'Chidi Nwosu',
    profession: 'Carpenter & Joiner',
    city: 'Port Harcourt',
    rating: 4.7,
    reviews: 62,
    hourlyRate: 6500,
    verified: true,
    bio: 'Custom furniture design and woodworking for homes and offices. 9 years building bespoke pieces across the South-South.',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&h=120&fit=crop&auto=format',
    cover: '',
    category: 'Carpentry',
    available: false,
    portfolio: [],
    services: [],
    reviews_list: [],
  },
  {
    id: 'mock-4',
    name: 'Amaka Okonkwo',
    profession: 'Painter & Decorator',
    city: 'Lagos, Yaba',
    rating: 4.9,
    reviews: 201,
    hourlyRate: 5000,
    verified: true,
    bio: 'Interior and exterior painting specialist. Colour consultation, textured finishes, and Venetian plaster applications.',
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=120&h=120&fit=crop&auto=format',
    cover: '',
    category: 'Painting',
    available: true,
    portfolio: [],
    services: [],
    reviews_list: [],
  },
  {
    id: 'mock-5',
    name: 'Yusuf Garba',
    profession: 'Auto Mechanic',
    city: 'Kano, Sabon Gari',
    rating: 4.6,
    reviews: 47,
    hourlyRate: 5500,
    verified: false,
    bio: 'Toyota & Nissan certified mechanic. Engine diagnostics, gearbox overhaul, AC servicing, and tyre replacements.',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&h=120&fit=crop&auto=format',
    cover: '',
    category: 'Auto Repair',
    available: true,
    portfolio: [],
    services: [],
    reviews_list: [],
  },
  {
    id: 'mock-6',
    name: 'Ngozi Adeyemi',
    profession: 'Interior Designer',
    city: 'Lagos, Lekki',
    rating: 5.0,
    reviews: 58,
    hourlyRate: 15000,
    verified: true,
    bio: 'Award-winning interior designer with projects across West Africa. Space planning, furniture sourcing, and full project management.',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&h=120&fit=crop&auto=format',
    cover: '',
    category: 'Carpentry',
    available: true,
    portfolio: [],
    services: [],
    reviews_list: [],
  },
]

export const CATEGORIES: Category[] = [
  { name: 'Plumbing', count: 142 },
  { name: 'Electrical', count: 98 },
  { name: 'Carpentry', count: 75 },
  { name: 'Painting', count: 120 },
  { name: 'Auto Repair', count: 63 },
  { name: 'Home Cleaning', count: 210 },
  { name: 'Tailoring', count: 84 },
  { name: 'Tiling & Flooring', count: 57 },
]

export const NIGERIAN_CITIES = [
  'Lagos', 'Abuja (FCT)', 'Kano', 'Port Harcourt',
  'Ibadan', 'Enugu', 'Benin City', 'Kaduna', 'Jos', 'Owerri',
]
